name: Trakke
options:
  bundleIdPrefix: no.tazk
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.2"
  generateEmptyDirectories: true
  groupSortPosition: top
  developmentLanguage: nb

packages:
  MapLibreNative:
    url: https://github.com/maplibre/maplibre-gl-native-distribution
    from: "6.23.0"
  MapLibreSwiftUI:
    url: https://github.com/maplibre/swiftui-dsl
    from: "0.21.1"
  MGRS:
    url: https://github.com/ngageoint/mgrs-ios
    from: "2.0.0"

settings:
  base:
    SWIFT_VERSION: "6.2"
    MARKETING_VERSION: "1.2.0"
    CURRENT_PROJECT_VERSION: 1
    SWIFT_STRICT_CONCURRENCY: complete
    SWIFT_COMPILATION_MODE: wholemodule
    COMPILATION_CACHING: YES
  configs:
    Debug:
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
      ENABLE_TESTABILITY: YES
      DEBUG_INFORMATION_FORMAT: "dwarf"
    Release:
      SWIFT_OPTIMIZATION_LEVEL: "-O"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: ""
      ENABLE_TESTABILITY: NO
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
      STRIP_INSTALLED_PRODUCT: YES
      COPY_PHASE_STRIP: YES

targets:
  Trakke:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Trakke
    settings:
      base:
        INFOPLIST_FILE: Trakke/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: no.tazk.trakke
        PRODUCT_NAME: "Trakke"
        INFOPLIST_KEY_CFBundleDisplayName: "Tråkke"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.navigation"
        INFOPLIST_KEY_UIBackgroundModes: "location"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: false
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
        DEVELOPMENT_TEAM: 8NW62A7PRA
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: MapLibreNative
        product: MapLibre
      - package: MapLibreSwiftUI
      - package: MGRS
        product: MGRS
    entitlements:
      path: Trakke/Trakke.entitlements
      properties: {}

  TrakkeTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: TrakkeTests
    dependencies:
      - target: Trakke
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: no.tazk.trakke.tests
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: false
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: false
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
        GENERATE_INFOPLIST_FILE: YES

  TrakkeUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: TrakkeUITests
    dependencies:
      - target: Trakke
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: no.tazk.trakke.uitests
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: false
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: false
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
        GENERATE_INFOPLIST_FILE: YES
