name: Trakke
options:
  bundleIdPrefix: no.tazk
  deploymentTarget:
    iOS: "26.2"
  xcodeVersion: "26.2"
  generateEmptyDirectories: true
  groupSortPosition: top

packages:
  MapLibreNative:
    url: https://github.com/maplibre/maplibre-gl-native-distribution
    from: "6.23.0"
  MapLibreSwiftUI:
    url: https://github.com/maplibre/swiftui-dsl
    from: "0.21.1"
  MGRS:
    url: https://github.com/ngageoint/mgrs-ios
    from: "2.0.0"
  Projections:
    url: https://github.com/ngageoint/projections-ios
    from: "3.0.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: 1
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  Trakke:
    type: application
    platform: iOS
    deploymentTarget: "26.2"
    sources:
      - path: Trakke
    settings:
      base:
        INFOPLIST_FILE: Trakke/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: no.tazk.trakke
        PRODUCT_NAME: "Trakke"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: false
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: MapLibreNative
        product: MapLibre
      - package: MapLibreSwiftUI
      - package: MGRS
        product: MGRS
      - package: Projections
        product: Projections
    entitlements:
      path: Trakke/Trakke.entitlements
      properties: {}

  TrakkeTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: TrakkeTests
    dependencies:
      - target: Trakke
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: no.tazk.trakke.tests
        GENERATE_INFOPLIST_FILE: YES

  TrakkeUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: TrakkeUITests
    dependencies:
      - target: Trakke
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: no.tazk.trakke.uitests
        GENERATE_INFOPLIST_FILE: YES
